---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-demo
  labels:
      app: cron-job-demo
  namespace: cron-job-demo
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 5
  startingDeadlineSeconds: 30
  ##concurrencyPolicy: Allow
  ##concurrencyPolicy: Forbid
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      backoffLimit: 1
      #activeDeadlineSeconds: 30
      template:
        spec:
          #completions: 5
          #parallelism: 2
          #backoffLimit: 15
          #activeDeadlineSeconds: 100
          #ttlSecondsAfterFinished: 100
          containers:
          - name: cron-job-demo
            image: neotkm/pod-healthcheck:v0.04
            command: ["sh"]
            args: ["-c",  "ls -lh"]
          restartPolicy: Never
          #restartPolicy: OnFailure
